--- 
title: "Web Forms Style Guide"
author: "Deirdre Moore"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a handbook of best practices and style suggestions for web forms."
---

# Introduction

In their book Forms That Work, Caroline Jarrett and Gerry Gaffney define a form as a conversation between two parties.  The core function of a form is to ask questions and record answers given

Users don’t want to fill out the form 

Helpful, transparent short

Who are Stanford’s users smart forced to complete

What is a good form


<!--chapter:end:index.Rmd-->

# Form Design {#formDesign}

## Best Practices 

### Make forms as short as possible
Every additional question on a form reduces the completion rate and data quality, while also increasing the rate of errors. designing-ux-forms/ Fatigue from answering questions  Ask yourself if the question/information can be inferred, postponed, or completely excluded. https://medium.com/nextux/form-design-best-practices-9525c321d759

### Multiple screens or a single page? 
If there are only one or two topics, a single page form is your best bet. But if a form has multiple sections, multiple pages are required to break up the conversation. Displaying only five to seven input fields at a given time is a common practice.

1. Find out the most common screen sizes—including mobile and tablet—for your target audience (that is, the sizes that are used by at least 60% of people who’ll use your form).
2. If the form can fit on three or fewer screenfuls of the most common sizes, leave it as one screen.
3. Otherwise, break the form up into separate screens, one step per screen.
4. Avoid having more than seven screens


https://xd.adobe.com/ideas/principles/web-design/best-practices-form-design/
Each approach has a number of advantages and disadvantages, which I Jessica Enders Create Forms Enders, J. (2016). Designing UX: Forms. won’t go into here. Instead, I’ll offer this simple formula: 
  https://www.stylemanual.gov.au/content-types/forms#choose_accessible_form_inputs

/designing-ux-forms/

### Keep a single column format 
Splitting information across 2 or more columns can:
* add cognitive load for users
* slow down users of assistive technology
* make the form harder to use on mobile devices.

### Principles for Deciding Question Order 

#### Follow How the User Thinks 
The order of questions in your form should, as closely as possible, match the way things flow in the user’s mind, so user research is essential. 

#### Core Before Supplementary 
Collect the information that’s central to your form’s purpose first, before collecting any supplementary information. That way, the most relevant and important data is provided when the user is freshest and most engaged with the form. Required fields before optional. 

#### Easy Before Difficult
Ask simpler and less intrusive questions before complex and more intrusive questions. This eases users into the process instead of bombarding them with hard stuff up front. It also ensures users are more committed before being presented with questions that may otherwise have tempted them to turn away.

This progress indicator from a personal loan application shows that easier questions—like contact details—are asked before more challenging questions—like financial details.

#### Related Together 
The rule of thumb is that the closer in topic questions are, the closer they should physically be placed together. The more related questions are, the closer they should be to each other in the form. (Demographic info, exam results etc)

### Minimal Color 
Reserve color for things that need it, so they stand out in some way. Buttons, error messages, links, headings, backgrounds etc are good examples. Be sparing, the more color you use, the less it stands out. Reminder, you never want to rely solely on color to communicate something in your web form. 

### Form must be accessible 
In order to be considered accessible, form components must meet the following success criterion from the Web Content Accessibility Guidelines :

** (WCAG) 2.0: 4.1.2 ** Name, Role, Value: For all user interface components (including but not limited to: form elements, links, and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.

The good news is that standard HTML elements already meet these requirements, providing an accessible user experience without additional code to accommodate assistive technology.  It is only if you are using custom elements that you will have to implement the guidelines. you are.

Assuming your form components are accessible, ddd suggests UX design suggests the following 

* Ensure the form has a proper contrast between foreground and background.
* Some people cannot read the text if there is not sufficient contrast between the text and the background (see minimum contrast ratio as required by WCAG.) https://uit.stanford.edu/accessibility/concepts/color/checker
* Allow users to control text size: 
People with low vision and cognitive disabilities require increased font size to read. A product designer should provide controls that allow the user to incrementally increase or decrease the text size.
* Screen Reader Enable: 
Make sure to include the label attribute for screen readers and if sectionioning your form, tag the groups for screen readers.
* Don’t rely on color as the only visual means to communicate status. 
An estimated eight percent of males and one percent of females are color blind, according to Prevent Blindness, so provide additional identification for color-blind people (e.g. an error message with red text can also contain an exclamation point icon.)	

### Pre-fill fields when possible 
Reduce the burden of typing as much as possible. Use pre-filled information if available and appropriate for the user and make use of smart defaults (e.g. If requesting phone # or country can default value based on the user's IP address). Browsers like Google Chrome & Firefox now have an auto-fill function that lets users fill out standard form fields in one click. For this to work, Google Chrome / Firefox look for contextual clues in the ‘name’, ‘label’, and placeholder text. Therefore, it’s good practice to ensure your fields are properly tagged with terms that a browser would recognise e.g. ‘email’, ‘first name’, or ‘city’. Autofocus on first input  field
 
### Use Progressive disclosure (Conditional logic)
A form can reveal more content as users go through the form and use its fields and controls. This technique can be used when it is not necessary to see all controls unless users have made specific decisions, for example, if they ticked a particular checkbox additional information would be revealed.
 
### Keep tab order consistent with input order
Make sure the user can freely navigate through the form without a mouse (e.g. people with a tablet device or those using screen readers).  Match the tab order to the visual order in which questions, buttons and other elements are presented. 

### Distinguish Optional and Required fields:
There are some legitimate situations where forms have far more optional questions than required ones. In this situation, simply reverse the advice:

Have an instruction, at the top of each screen, that says: “All questions are optional, unless marked (required).”
Add “(required)” to the end of the label for every required question.
Don’t add any visual markers to optional fields.

A much better approach is to only indicate the optional fields:

Have an instruction, at the top of each screen, that says: “All questions must be answered, unless marked (optional).”
Add “(optional)” to the end of the label for every optional question.
Don’t add any visual markers to required fields.
This method  Highly accessible & usable, while also reducing the amount of visual noise.

### Align fields
“illuminate a clear path to completion. Aligning inputs and actions with a strong vertical axis clearly communicates how to go about completing a form.”

### 

### Every page should have a form title and step progress for multiple page forms

use sentence case throughout your form, including headings

### Have a gateway and confirmation screen

#### Gateway screen 
should contain A title and friendly message  followed by a brief description of what the respondent can expect from the form., (if they need anything, how long to complete etc). Can be a login screen. 

#### Confirmation screen
Sends a success or fail message and what to expect next. Thank you for completing, successful submission, next steps. Can also send an email confirmation. 
If there is a delay after submit, use a processing screen to feedback to the user that something is happening. 





<!--chapter:end:01-formDesign.Rmd-->

# Form Components




https://uxplanet.org/the-anatomy-of-input-field-c3ef863e01d7

## Component Types

### Input text field


#### Best Practices: 

##### Use field length as an affordance 
Set the size of the text input box to the size of the response the user will provide. 

##### User should be able to judge the state of the field. 
Field focus should be a visual cue – such as changing the color of the border or background of the selected input field, or simply showing the cursor in the input field. Think of it as a hint you leave users regarding where they are.

Input field consists of the following parts:

1. Container/Border
1. Label
1. Placeholder/Input text
1. Trailing icon (Optional element)
1. Helper text/Error text (Optional element)
1. Leading icon (Optional element)

#### Container 
Say something about the container

##### Label 
Use sentence case

##### Input text or Placeholder text 
Use placeholder text for instructions only e.g. Please select… or DD/MM/YYYY. There should be a very clear distinction between the placeholder itself and the value typed by the respondent. If there is not, the respondent might think that the fields with placeholders are already filled fields.

##### Icons
Icons can be effective labels when they are easy to decipher, either because their meaning is clear or because they are familiar, such as the text formatting icons used on most text editor toolbars. When the meaning is not clear, icons are best paired with descriptive text. The icons are easy to visually scan and recognize, and the text provides additional clarity about the purpose of the control.
https://www.webstyleguide.com/7-interface-design.html

##### Help text 
Position the help text between the label and the input field. Don’t use headings, labels or placeholder text for help text.


Image from https://www.stylemanual.gov.au/content-types/forms#choose_accessible_form_inputs


### Radio Buttons
Radio buttons are used for mutually exclusive choices 
#### Best Practices: 

##### All options should be visible. 
Users must be able to scan and compare options to make an appropriate selection 

#####  Vertically align the buttons 
When possible, arrange the radio buttons vertically for easier reading. If the choice is limited to binary or opposite (light/dark) options, then they can be aligned horizontally.  



### Links
Links should open on a new window to preserve cursor position, and flow of form input 




<!--chapter:end:02-formComponents.Rmd-->

# Methods

We describe our methods in this chapter.

Math can be added in body using usual syntax like this 

## math example

$p$ is unknown but expected to be around 1/3. Standard error will be approximated

$$
SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
$$

You can also use math in footnotes like this^[where we mention $p = \frac{a}{b}$].

We will approximate standard error to 0.027[^longnote]

[^longnote]: $p$ is unknown but expected to be around 1/3. Standard error will be approximated

    $$
    SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
    $$

<!--chapter:end:03-method.Rmd-->

# Applications

Some _significant_ applications are demonstrated in this chapter.

## Example one

## Example two

<!--chapter:end:04-application.Rmd-->

# Final Words

We have finished a nice book.

<!--chapter:end:05-summary.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:06-references.Rmd-->

